### PR TITLE
improve readability for code-blocks in upgrading guides

### PR DESCRIPTION
**Pull request by steffkes**
instead of using those `BEFORE` and `AFTER` blocks, i propose that we're using typical diffs that everyone should be able to read. especially for the larger blocks it's sometimes hard to spot the difference between before and after.

### CODE REVIEW

**Comment by danielberkompas** [comment]
@steffkes Unfortunately, it's a catch-22. The diffs are easier to read on Github, but potentially harder to read on Hex docs, which is where I expect most people will be reading them. `ex_doc` doesn't support `diff` syntax highlighting.

**Comment by steffkes** [comment]
ah, got it .. didn't think about `ex_doc` at all, my bad - sorry for that. in that case, feel free to discard this suggestion.

**Comment by steffkes** [comment]
just checked hexdocs .. if you'd asked me, i'd say the diff is still more readable than the before/after block. even w/o the code-highlighting, that's just kicking in otherwise. i'll have a look at how `ex_doc` works with the code blocks

**Comment by danielberkompas** [comment]
@steffkes Honestly, it's probably a personal preference thing. Some people like to see the exact changes they need to make: other people like to see the "final state" of what it should look like after the changes are made. 

If we can get some better code fence support into ex_doc, I'd be happy to include both approaches, but for now, I think leaving it this way is fine. Thanks for the suggestion though! :star:

**Pull request closed without merging**
