### PR TITLE
Support _routing meta-field

### PR DESCRIPTION
**Pull request by cdunn**
Add a new optional protocol DocumentMeta that adds the ability to specify a _routing key.  This allows specific shard targeting which is required for `join` fields.

* https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-routing-field.html
* https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html

@danielberkompas let me know if you think this is the right approach and I can add a few more tests.

### CODE REVIEW

**Comment by danielberkompas** [comment]
@cdunn thanks for this! I'm wondering if we could just incorporate a new `routing` function into the existing `Document` protocol, rather than creating a new protocol.

```
defimpl Elasticsearch.Document, for: MyApp.Type do
  # if you don't want to use routing, just return false
  def routing(_document), do: false

  # if you want to use routing, do this:
  def routing(document) do
    # ...
  end
end
```

**Comment by cdunn** [comment]
@danielberkompas sounds good.  I agree it's cleaner as a single protocol...I originally tried that but couldn't figure out if there was a way to make just the routing function `fallback_to_any` and false it there by default so it wouldn't be a breaking change given that most folks probably don't use it to start.  Will consolidate and document later but let me know if you can think of any way to make this non-breaking.

**Comment by danielberkompas** [comment]
I don't think it matters too much if it's a breaking change. The library is still <1.0.0 at this point, so breaking changes are not a really big problem. As long as we write a good upgrade guide, I think it will be fine.

**Comment by danielberkompas** [comment]
This looks great, thanks! I'll try and get a new version released over the weekend.

**Pull request merged**
